# Generated by Django 4.0.1 on 2022-02-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='changed_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
