# Generated by Django 3.2.8 on 2021-11-15 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faces',
            new_name='Face',
        ),
    ]
