# Generated by Django 3.2.9 on 2021-11-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_api', '0002_rename_faces_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='face',
            field=models.ImageField(upload_to='images'),
        ),
    ]
