# Generated by Django 3.2.9 on 2021-11-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_api', '0008_face_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
